create schema if not exists notes;

create table notes.note_access_type (
	note_access_type     varchar(7)   primary key,
	name_ukr             varchar(50)  not null,
	name_eng             varchar(50)  not null
);

create unique index ix_note_access_type on notes.note_access_type(note_access_type);

comment on table  notes.note_access_type                   is 'Типи доступу до нотатки';
comment on column notes.note_access_type.note_access_type  is 'Типи доступу до нотатки';
comment on column notes.note_access_type.name_ukr          is 'Найменування типу доступу українською';
comment on column notes.note_access_type.name_eng          is 'Найменування типу доступу англійською';

create table notes.note (
	note_id              uuid         primary key,
	title                varchar(100) not null check(length(title) between 5 and 100),
	content              text         not null check(length(content) between 5 and 10000),
	note_owner           uuid         not null,
	note_access_type     varchar(7)   not null,
	created_date         timestamp,
	updated_date         timestamp,
	constraint fk_note_users foreign key(note_owner) references access.users(user_id)
);
create unique index ix_note_note_id        on notes.note(note_id);
create        index ix_note_user_id        on notes.note(note_owner);

comment on table  notes.note                    is 'Нотатки';
comment on column notes.note.note_id            is 'ID нотатки';
comment on column notes.note.title              is 'Заголовок нотатки';
comment on column notes.note.content            is 'Вміст нотатки';
comment on column notes.note.note_owner         is 'Власник нотатки';
comment on column notes.note.note_access_type   is 'Тип доступу до нотатки';
comment on column notes.note.created_date       is 'Дата створення нотатки';
comment on column notes.note.updated_date       is 'Дата останнього коригування нотатки';

create table notes.tag (
	tag_id               uuid             primary key,
	title                varchar(100)     not null,
	created_date         timestamp,
	updated_date         timestamp
);
create unique index ix_tag_tag_id        on notes.tag(tag_id);

comment on table  notes.tag                    is 'Теги нотатків';
comment on column notes.tag.tag_id             is 'ID тегу';
comment on column notes.tag.title              is 'Найменування тегу';
comment on column notes.tag.created_date       is 'Дата створення тегу';
comment on column notes.tag.updated_date       is 'Дата останнього коригування тегу';

create table notes.note_tag (
	note_tag_id          bigint generated by default as identity(start with 1) primary key,
	note_id              uuid   not null,
	tag_id               uuid   not null,
	created_date         timestamp,
	updated_date         timestamp,
	constraint fk_note_tag_note foreign key(note_id) references notes.note(note_id),
	constraint fk_note_tag_tag foreign key(tag_id) references notes.tag(tag_id)
);

create unique index ix_note_tag_note_tag_id        on notes.note_tag(note_tag_id);
create unique index ix_note_tag_note_id            on notes.note_tag(note_id);
create unique index ix_note_tag_tag_id             on notes.note_tag(tag_id);

comment on table  notes.note_tag               is 'Звязок нотатку з тегами';
comment on column notes.note_tag.note_tag_id   is 'ID звязку нотатку з тегом';
comment on column notes.note_tag.note_id       is 'ID нотатку';
comment on column notes.note_tag.tag_id        is 'ID тегу';
comment on column notes.note_tag.created_date  is 'Дата створення звязку';
comment on column notes.note_tag.updated_date  is 'Дата останнього коригування звязку';